// <auto-generated />
using System;
using LoanManagement.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoanManagement.Migrations
{
    [DbContext(typeof(LoanMgmtContext))]
    [Migration("20190714085001_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoanManagement.Domain.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("InterestRate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 7, 14, 18, 50, 1, 357, DateTimeKind.Local).AddTicks(1974),
                            InterestRate = 3.5,
                            Name = "asd",
                            Type = "Personal",
                            UpdatedOn = new DateTime(2019, 7, 14, 18, 50, 1, 358, DateTimeKind.Local).AddTicks(5245)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2019, 7, 14, 18, 50, 1, 358, DateTimeKind.Local).AddTicks(5767),
                            InterestRate = 4.5,
                            Name = "dfe",
                            Type = "Personal",
                            UpdatedOn = new DateTime(2019, 7, 14, 18, 50, 1, 358, DateTimeKind.Local).AddTicks(5777)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2019, 7, 14, 18, 50, 1, 358, DateTimeKind.Local).AddTicks(5782),
                            InterestRate = 2.5,
                            Name = "wer",
                            Type = "Personal",
                            UpdatedOn = new DateTime(2019, 7, 14, 18, 50, 1, 358, DateTimeKind.Local).AddTicks(5785)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
