// <auto-generated />
using System;
using LoanManagement.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoanManagement.Migrations
{
    [DbContext(typeof(LoanMgmtContext))]
    partial class LoanMgmtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoanManagement.Domain.LoanMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("InterestRate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("LoanMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 593, DateTimeKind.Local).AddTicks(8861),
                            InterestRate = 3.5,
                            Name = "asd",
                            Type = "Personal",
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(970)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(1413),
                            InterestRate = 4.5,
                            Name = "dfe",
                            Type = "Personal",
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(1421)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(1426),
                            InterestRate = 2.5,
                            Name = "wer",
                            Type = "Personal",
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(1428)
                        });
                });

            modelBuilder.Entity("LoanManagement.Domain.UserLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AppliedForTopup");

                    b.Property<double>("Balance");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("EarlyPaymentFee");

                    b.Property<double>("InterestAmount");

                    b.Property<int>("LoanMasterId");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<int>("UserId");

                    b.Property<string>("UserLoanNum")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LoanMasterId");

                    b.ToTable("UserLoans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliedForTopup = false,
                            Balance = 1870.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5453),
                            EarlyPaymentFee = 67.0,
                            InterestAmount = 324.0,
                            LoanMasterId = 1,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5460),
                            UserId = 1,
                            UserLoanNum = "678523187"
                        },
                        new
                        {
                            Id = 2,
                            AppliedForTopup = false,
                            Balance = 1902.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5488),
                            EarlyPaymentFee = 34.0,
                            InterestAmount = 546.0,
                            LoanMasterId = 1,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5490),
                            UserId = 2,
                            UserLoanNum = "345785234"
                        },
                        new
                        {
                            Id = 3,
                            AppliedForTopup = false,
                            Balance = 3234.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5494),
                            EarlyPaymentFee = 267.0,
                            InterestAmount = 233.0,
                            LoanMasterId = 2,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5495),
                            UserId = 2,
                            UserLoanNum = "432578456"
                        },
                        new
                        {
                            Id = 4,
                            AppliedForTopup = false,
                            Balance = 4678.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5498),
                            EarlyPaymentFee = 464.0,
                            InterestAmount = 234.0,
                            LoanMasterId = 2,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5500),
                            UserId = 3,
                            UserLoanNum = "245356733"
                        },
                        new
                        {
                            Id = 5,
                            AppliedForTopup = false,
                            Balance = 1647.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5502),
                            EarlyPaymentFee = 89.0,
                            InterestAmount = 456.0,
                            LoanMasterId = 1,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5504),
                            UserId = 3,
                            UserLoanNum = "234677345"
                        },
                        new
                        {
                            Id = 6,
                            AppliedForTopup = false,
                            Balance = 1094.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5509),
                            EarlyPaymentFee = 102.0,
                            InterestAmount = 343.0,
                            LoanMasterId = 2,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5511),
                            UserId = 3,
                            UserLoanNum = "549785345"
                        },
                        new
                        {
                            Id = 7,
                            AppliedForTopup = false,
                            Balance = 2644.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5513),
                            EarlyPaymentFee = 98.0,
                            InterestAmount = 123.0,
                            LoanMasterId = 3,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5515),
                            UserId = 4,
                            UserLoanNum = "456845676"
                        },
                        new
                        {
                            Id = 8,
                            AppliedForTopup = false,
                            Balance = 2355.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5518),
                            EarlyPaymentFee = 74.0,
                            InterestAmount = 435.0,
                            LoanMasterId = 3,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5520),
                            UserId = 4,
                            UserLoanNum = "345689678"
                        },
                        new
                        {
                            Id = 9,
                            AppliedForTopup = false,
                            Balance = 2345.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5522),
                            EarlyPaymentFee = 82.0,
                            InterestAmount = 265.0,
                            LoanMasterId = 3,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5524),
                            UserId = 4,
                            UserLoanNum = "985467845"
                        },
                        new
                        {
                            Id = 10,
                            AppliedForTopup = false,
                            Balance = 2345.0,
                            CreatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5527),
                            EarlyPaymentFee = 82.0,
                            InterestAmount = 265.0,
                            LoanMasterId = 3,
                            UpdatedOn = new DateTime(2019, 7, 17, 2, 3, 37, 595, DateTimeKind.Local).AddTicks(5529),
                            UserId = 4,
                            UserLoanNum = "985435846"
                        });
                });

            modelBuilder.Entity("LoanManagement.Domain.UserLoan", b =>
                {
                    b.HasOne("LoanManagement.Domain.LoanMaster", "LoanMaster")
                        .WithMany()
                        .HasForeignKey("LoanMasterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
